"""TypeScript code evaluators for Langfuse (insecure-local dispatcher)."""


def _ts(lines: list[str]) -> str:
    """Join lines into a single source string."""
    return "\n".join(lines)


CODE_EVALUATORS = [
    {
        "name": "JSON Parseable Output",
        "description": "Checks if the observation output is valid JSON",
        "type": "code",
        "sourceCode": _ts([
            "function evaluate({ observation }: EvaluationContext): EvaluationResult {",
            "  const output = observation.output;",
            "  if (output == null) {",
            "    return { scores: [{ name: 'JSON Parseable', value: false, dataType: 'BOOLEAN', comment: 'Output is null or undefined' }] };",
            "  }",
            "  let isValid = false;",
            "  let comment = '';",
            "  try {",
            "    const raw = typeof output === 'string' ? output : JSON.stringify(output);",
            "    JSON.parse(raw);",
            "    isValid = true;",
            "    comment = 'Output is valid JSON';",
            "  } catch {",
            "    isValid = false;",
            "    comment = 'Output is not valid JSON';",
            "  }",
            "  return { scores: [{ name: 'JSON Parseable', value: isValid, dataType: 'BOOLEAN', comment }] };",
            "}",
        ]),
        "sourceCodeLanguage": "TYPESCRIPT",
    },
    {
        "name": "Output Not Empty",
        "description": "Checks if the observation output is present and non-empty",
        "type": "code",
        "sourceCode": _ts([
            "function evaluate({ observation }: EvaluationContext): EvaluationResult {",
            "  const output = observation.output;",
            "  const isPresent = output != null && String(output).trim() !== '';",
            "  return {",
            "    scores: [{",
            "      name: 'Output Not Empty',",
            "      value: isPresent,",
            "      dataType: 'BOOLEAN',",
            "      comment: isPresent ? 'Output is present and non-empty' : 'Output is missing or empty'",
            "    }]",
            "  };",
            "}",
        ]),
        "sourceCodeLanguage": "TYPESCRIPT",
    },
    {
        "name": "Exact Match",
        "description": "Checks if the output exactly matches the expected output in experiments",
        "type": "code",
        "sourceCode": _ts([
            "function evaluate({ observation, experiment }: EvaluationContext): EvaluationResult {",
            "  const expected = experiment?.itemExpectedOutput;",
            "  const output = observation.output;",
            "  const matches = expected != null && output === expected;",
            "  return {",
            "    scores: [{",
            "      name: 'Exact Match',",
            "      value: matches,",
            "      dataType: 'BOOLEAN',",
            "      comment: matches ? 'Output exactly matches expected output' : 'Output does not match expected output'",
            "    }]",
            "  };",
            "}",
        ]),
        "sourceCodeLanguage": "TYPESCRIPT",
    },
    {
        "name": "Contains Required Keywords",
        "description": "Checks if the output contains all required keywords from expected metadata",
        "type": "code",
        "sourceCode": _ts([
            "function evaluate({ observation, experiment }: EvaluationContext): EvaluationResult {",
            "  const output = String(observation.output ?? '').toLowerCase();",
            "  const metadata = experiment?.itemMetadata as Record<string, unknown> | undefined;",
            "  const keywords: string[] = Array.isArray(metadata?.required_keywords) ? metadata.required_keywords as string[] : [];",
            "  if (keywords.length === 0) {",
            "    return { scores: [{ name: 'Contains Required Keywords', value: true, dataType: 'BOOLEAN', comment: 'No required keywords specified' }] };",
            "  }",
            "  const missing = keywords.filter(kw => !output.includes(kw.toLowerCase()));",
            "  const allPresent = missing.length === 0;",
            "  const comment = allPresent ? 'All required keywords present' : `Missing keywords: ${missing.join(', ')}`;",
            "  return { scores: [{ name: 'Contains Required Keywords', value: allPresent, dataType: 'BOOLEAN', comment }] };",
            "}",
        ]),
        "sourceCodeLanguage": "TYPESCRIPT",
    },
    {
        "name": "Output Length Check",
        "description": "Scores the output length as a ratio against a max expected length",
        "type": "code",
        "sourceCode": _ts([
            "function evaluate({ observation }: EvaluationContext): EvaluationResult {",
            "  const output = String(observation.output ?? '');",
            "  const length = output.length;",
            "  const maxLength = 2000;",
            "  const withinLimit = length <= maxLength;",
            "  const ratio = Math.round(Math.min(length / maxLength, 1.0) * 100) / 100;",
            "  return {",
            "    scores: [",
            "      { name: 'Within Length Limit', value: withinLimit, dataType: 'BOOLEAN', comment: `Output length: ${length} chars (limit: ${maxLength})` },",
            "      { name: 'Length Ratio', value: ratio, dataType: 'NUMERIC', comment: `Output uses ${ratio * 100}% of max length` }",
            "    ]",
            "  };",
            "}",
        ]),
        "sourceCodeLanguage": "TYPESCRIPT",
    },
    {
        "name": "Tool Call Validator",
        "description": "Validates that tool calls have required name and arguments fields",
        "type": "code",
        "sourceCode": _ts([
            "function evaluate({ observation }: EvaluationContext): EvaluationResult {",
            "  const toolCalls = observation.toolCalls;",
            "  if (!toolCalls || toolCalls.length === 0) {",
            "    return { scores: [{ name: 'Tool Calls Valid', value: true, dataType: 'BOOLEAN', comment: 'No tool calls to validate' }] };",
            "  }",
            "  const invalid = toolCalls.filter(tc => !tc.name || tc.arguments == null).map(tc => tc.name || `index:${tc.index}`);",
            "  const allValid = invalid.length === 0;",
            "  const comment = allValid ? 'All tool calls have name and arguments' : `Invalid tool calls: ${invalid.join(', ')}`;",
            "  return {",
            "    scores: [",
            "      { name: 'Tool Calls Valid', value: allValid, dataType: 'BOOLEAN', comment },",
            "      { name: 'Tool Call Count', value: toolCalls.length, dataType: 'NUMERIC', comment: `${toolCalls.length} tool call(s) found` }",
            "    ]",
            "  };",
            "}",
        ]),
        "sourceCodeLanguage": "TYPESCRIPT",
    },
]
